### ISSUE TITLE
I don't know if this correct

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/ids-specification#119]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/357773cbbf875d45bfec95cabb3222b952cc7542/negotiation/message/example/contract.agreement.message.http.transfer.json#L14

... maybe we have to use "rdf:value" instead. But using the string only (so, not using an object) is fine, too.

**Comment by ssteinbuss** [comment]
Closed due to inactivity
