### ISSUE TITLE
dspace:TRANSPORT

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/ids-specification#120]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/357773cbbf875d45bfec95cabb3222b952cc7542/negotiation/message/example/contract.agreement.message.http.transfer.json#L16

Where ist defined?

**Comment by juliapampus** [comment]
This is an example.

**Comment by ssteinbuss** [comment]
Closed due to inactivity
