### ISSUE TITLE
dspace:HTTP_REST

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/ids-specification#121]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/357773cbbf875d45bfec95cabb3222b952cc7542/negotiation/message/example/contract.agreement.message.http.transfer.json#L18

Where is it defined?

**Comment by juliapampus** [comment]
This is an example.

**Comment by jlangkau** [comment]
Nice! But: can you please define (as an example 😎) "HTTP_REST", too?

**Comment by ssteinbuss** [comment]
Closed due to inactivity
