### ISSUE TITLE
assigner and assignee

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/ids-specification#123]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/357773cbbf875d45bfec95cabb3222b952cc7542/negotiation/message/example/contract.agreement.message.http.transfer.json#L6

...those are not used here? Why?

**Comment by Brandstaedter** [comment]
https://github.com/International-Data-Spaces-Association/ids-specification/pull/102

**Comment by juliapampus** [comment]
Answered within #102
