### ISSUE TITLE
ODRL PROFILE

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/ids-specification#126]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/7be42da128f6efbebb446ed41aebd7acda4fc7c6/model/model.md?plain=1#L74

...why is it mentioned here? What is the relation to "target"?

**Comment by jimmarino** [comment]
An agreement is always for exactly one asset/dataset. Note that an asset does not necessarily imply a single "data item, file, etc."

Also, the catalog specification profiles ODRL `Offer`s to not contain a target and be unique to a dataset.

**Comment by ssteinbuss** [comment]
Closed due to inactivity
