### ISSUE TITLE
typo in catalog http bindings

### ISSUE THREAD

**Issue by ndr-brt** [International-Data-Spaces-Association/ids-specification#128]
In the example at line 63 the `catalog/` path param is missing

https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.binding.https.md?plain=1#L56-L63

**Comment by sebbader-sap** [comment]
Agreement from the DSP group meeting today: Finding in correct and `/catalog` will be added in the example, too.
