### ISSUE TITLE
Negotiation consumer endpoint for provider initial offer

### ISSUE THREAD

**Issue by ronjaquensel** [International-Data-Spaces-Association/ids-specification#129]
As defined in the sequence diagram for contract negotiations, both provider and consumer should be able to initiate a new negotiation. Currently, only the consumer can do so, as in the negotiation HTTP bindings, there is no endpoint defined on the consumer side for receiving an initial offer from the provider. The provider may only send counter offers using the `{id}/offers` endpoint. Therefore I propose adding a new endpoint `/offers` (without id binding) for the consumer side with the same request format as `{id}/offers`

**Comment by sebbader-sap** [comment]
Decision from the call on 03.08.2023:

* `{id}/offers` stays, and
* a `/offers` endpoint it added

**Comment by juliapampus** [comment]
Add a new section `3.2 The consumer negotiations/offers resource` between the current 3.1 and 3.2 in [contract.negotiation.binding.https.md](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.binding.https.md). See 2.5 as reference:
- result state
- message
- path
- example POST with body
- result body
- ...
