### ISSUE TITLE
Rename DataspaceAuthority to Authority and DataspaceRegistrationService to RegistrationService

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/ids-specification#134]
In the context of Dataspaces we are talking about participants, thus we could also simply refer to authroity and omit the Dataspace in DataspaceAuthority. Otherwise, for consistency we would need to add Dataspace also to Participants, thus DataspaceParticipant. Same agurmentation applies to DataspaceRegistrationService.

https://github.com/International-Data-Spaces-Association/ids-specification/blob/71bc11c641a34685a72ab8e1d5eb9a8e298869df/model/terminology.md?plain=1#L9

**Comment by sebbader-sap** [comment]
From the discussion of today's (03.08.2023) call:
* Can there be a non-Dataspace Participant? --> hardly...
* Can there be more than one Authority? --> likely...
* Can there be more than one RegistrationService? --> probably...

**Comment by ssteinbuss** [comment]
Inactive
