### ISSUE TITLE
New Binding of Dataspace Protocol to TMForum APIs

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/ids-specification#144]
The TMForum APIs are widely used and adopted in the TelCo Domain. An additional Binding of the Dataspace Protocol to the TMForum APIs should be considered.
First thoughts on binding are available in [this slide deck](https://docs.google.com/presentation/d/1hE4yDZlj9vvKaIARvtwZYSOq9KDHD9g9xC4Wh7SbZlY/edit#slide=id.g2572633115a_0_48).

**Comment by ssteinbuss** [comment]
This is about the potential of TMForum to implement the Dataspace Protocol. 

The Dataspace Protocol Specification should remain unchanged, but a clear description how the TMForum APIs can be used to realize and implement the Dataspace Protocol.

This should start now in the Best Practices area.

**Comment by jimmarino** [comment]
The slides strike me more as a discussion of a particular DSP *implementation*, not a DSP binding to a transport. DSP bindings define how abstract protocol messages map to a particular transport such as `HTTP`, `MQTT`, etc. They don't define new concepts or message exchange patterns.

An analog to a DSP binding is a `WSDL` Binding.

**Comment by ssteinbuss** [comment]
This has not been continued recently. If we want to continue here, please reopen the issue.
