### ISSUE TITLE
Transitions from after AGREED to TERMINATED might be an issue from legal perspective

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#145]
In Catena-X we did map the state changes to legal perspective of how contracts are negotiated and it looks good.

Only 1 issue came up during the discussion. The state changes after AGREED to TERMINATED might be an issue, because a contract can not be 'terminated' from one side after successfully negotiated.

This is meant as an early heads up. Details (currently worked out from legal experts) will follow if required (probably after my vacation...)

--
Matthias Binzer

**Comment by juliapampus** [comment]
Consumer accepts -> provider agrees -> consumer has to verify. What if the verification of this agreement fails on consumer side? The provider is also allowed to transition to `TERMINATED` instead of `FINALIZED` after `VERIFIED`... this would be an issue from legal perspective too, right?

**Comment by SebastianOpriel** [comment]
If we talk about the implementation itself in Catena-X (i.e. EDC) we have a lot of more open points to obey, when it comes to legal aspects (at least in EU), like https://github.com/eclipse-tractusx/tractusx-edc/issues/673#issuecomment-1653075558 or the overall capability of EDC to adjust assets, etc. Same AGREED to TERMINATED transition will rely on local legal regulations. I am not aware if every country judges such a transition as non-legally compliant.

**Comment by jimmarino** [comment]
I think this is mixing concepts: the state changes are for a contract *negotiation*, not the contract itself.

**Comment by matgnt** [comment]
Good points. I'll check if AGREED and VERIFIED can be technical intermediate steps without any direct legal correlation. FINALIZED should be linked to a legal meaning again. Let's discuss on Thursday!

**Comment by juliapampus** [comment]
Some links to the rulebook @matgnt 
- Legal as guiding principle: https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/2_guiding_principles#l-legal
- Visualization of policy types: https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/3_functional_requirements#policies
- Legal regulations etc.: https://docs.internationaldataspaces.org/ids-knowledgebase/v/idsa-rulebook/idsa-rulebook/6_legal_dimension

**Comment by matgnt** [comment]
Closing the issue. No longer relevant here in the Spec.
