### ISSUE TITLE
Adopt a methodology for versioning Json-Ld contexts 

### ISSUE THREAD

**Issue by jimmarino** [International-Data-Spaces-Association/ids-specification#147]
This has two aspects:

1. We should adopt the pattern developed by W3C for Json-Ld context versioning:

`https://www.w3id.org/2023/dspace/v1`

See [here](https://github.com/w3c/wot-thing-description/issues/442)

2. We should use`w3id.org` to resolve context URLs.

**Comment by ssteinbuss** [comment]
Options:

* https://w3id.org/dspace/2023/v1 
* https://w3id.org/dspace/v1

IDSA needs to acquire w3id.org/dspace namespace and add a list of maintainers there.

**Comment by ssteinbuss** [comment]
started to acquire the dspace w3id https://github.com/International-Data-Spaces-Association/w3id.org/tree/master/dspace

**Comment by ssteinbuss** [comment]
* Please check the content of the [READMEmd](https://github.com/International-Data-Spaces-Association/w3id.org/blob/master/dspace/README.md).
* Please add your contact information when appropriate to the [README.md](https://github.com/International-Data-Spaces-Association/w3id.org/blob/master/dspace/README.md#contact)
* Which rewrite rules do we need to put into the [.htaccess](https://github.com/International-Data-Spaces-Association/w3id.org/blob/master/dspace/.htaccess) ?

**Comment by matgnt** [comment]
summary of the meeting today:
- we can not use raw links to the context because of rate limits (other projects had already...)
- either use gitbook or github page to publish the context.json document and then add it to the .htaccess file as a forwarding rule.

**Comment by sebbader-sap** [comment]
Decision as of 28.09.2023:

### JSON-LD Context versioning topic:
Option 3: `https://w3id.org/dspace/v<major>[.<minor>]` --> e.g. https://w3id.org/dspace/v1.1 and https://w3id.org/dspace/v2

### Hosting location of the context file:
Option 0: Start with an W3ID link to the Github raw file and move the file/adjust the link if some quota actually is reached.

**Comment by sebbader-sap** [comment]
Left before closing the issue:

- [ ] adjust context URL everywhere. New one is https://w3id.org/dspace/v0.8

**Comment by sebbader-sap** [comment]
I am closing it as https://github.com/International-Data-Spaces-Association/ids-specification/issues/224#issuecomment-1945687346 contains all what we will do for this topic as much as this repo is affected.
