### ISSUE TITLE
TBD: Versioning

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#15]
Resolve TBD in  `catalog.binding.https.md`.

**Comment by ssteinbuss** [comment]
The section [3.2 Versioning](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.binding.https.md#32-versioning) is missing text:

- How do you discover the base URI for the different versions of the catalog API --> HTTP binding
- Option A: Standalone Catalog
- Option B: Connector and Catalog hosted under one base URL

**Comment by ssteinbuss** [comment]
@jimmarino and @sebbader-sap could you sketch a solution?

**Comment by jimmarino** [comment]
Some thoughts:

1. Define a generic JSON response type, and each binding document will provide the mechanics for obtaining the metadata (e.g., `well-known` for HTP)
2. Each version can specify an endpoint

An example:

```json
{
   "versions": [
       { "1.0" : "https://example.com/catalog/v1"},
       { "2.0" : "https://example.com/catalog/v2"},
    ]
}
```

This should be part of #167.

**Comment by ssteinbuss** [comment]
fixed in #184

**Comment by sebbader-sap** [comment]
Explanation already introduced at https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/common/common.binding.https.md

**Comment by sebbader-sap** [comment]
Together with #225 and the linked explanation above, I'd say this issue is solved. Can somebody else confirm?

**Comment by ssteinbuss** [comment]
Agree.
