### ISSUE TITLE
Inconsistent negotiation schemas (odrl:offer & odrl:agreement)

### ISSUE THREAD

**Issue by mkollenstart** [International-Data-Spaces-Association/ids-specification#159]
In the schemas for negotiation the properties `odrl:offer` and `odrl:agreement` are used, while in the diagrams, examples, and shapes `dspace:offer` and `dspace:agreement` are used.

Given the fact that `offer` and `agreement` are not properties in the ODRL model, the message schemas should be updated to use `dspace:offer` and `dspace:agreement`

https://github.com/International-Data-Spaces-Association/ids-specification/blob/e3f09b310b9cb5983731d79e9184feae4d6e754a/negotiation/message/schema/contract-request-message-schema.json#L37-L40

https://github.com/International-Data-Spaces-Association/ids-specification/blob/e3f09b310b9cb5983731d79e9184feae4d6e754a/negotiation/message/schema/contract-offer-message-schema.json#L33-L36

https://github.com/International-Data-Spaces-Association/ids-specification/blob/e3f09b310b9cb5983731d79e9184feae4d6e754a/negotiation/message/schema/contract-agreement-message-schema.json#L33-L71

**Comment by sebbader-sap** [comment]
Will be part of #89. Thanks for raising the point!
