### ISSUE TITLE
Add a well-known endpoint for catalog requests

### ISSUE THREAD

**Issue by jimmarino** [International-Data-Spaces-Association/ids-specification#161]
A participant catalog may contain protected `Datasets` that require some proof to access. The mechanism for preseting a proof during a catalog request is outside the scope of the DSP Catalog Specification and should be detailed in a separate trust specification. For example, a trust specification may rely on W3C `Verifiable Credentials` and `Verifiable Presentations` as proof.

However, all trust specifications will require a mechanism for a client to discover which proof mechanisms are required to access protected catalog `Datasets.` The format of this metadata is specific to the trust specification, but the endpoint should be defined using a [Well-Known Uniform Resource Identifiers](https://www.rfc-editor.org/rfc/rfc8615.html).

The proposal is to add the following endpoint to the catalog specification:

`/.well-known/dspace-trust` 

The contents of the response is a JSON object defined by individual trust specifications.

**Comment by sebbader-sap** [comment]
Task 1:
- [ ] Verify whether  https://example.com/path-to-my-connector/.well-known/ is explicitly prohibited by the RFC.

Task 2: Decide on pattern for catalog vs. general trust information:
https://example.com/.well-known/dspace-catalog-trust
https://example.com/.well-known/dspace-trust
--> Decision: This is the pattern we want to use.

**Comment by ssteinbuss** [comment]
@sebbader-sap  means RFC 8615

**Comment by ssteinbuss** [comment]
We might want to add a note on multiple connectors under the same URI:

- Connectors could use different sub-domains, but if they are not using sub-domains, then
- probably the well-known endpoint cannot be used

**Comment by jimmarino** [comment]
> We might want to add a note on multiple connectors under the same URI:
> 
> * Connectors could use different sub-domains, but if they are not using sub-domains, then
> * probably the well-known endpoint cannot be used

They could use this by appending a path segment to the base well-known URL. Section 3 states:

>Registrations MAY also contain additional information, such as the
   syntax of additional path components, query strings, and/or fragment
   identifiers to be appended to the well-known URI, or protocol-
   specific details (e.g., HTTP [[RFC7231](https://datatracker.ietf.org/doc/html/rfc7231)] method handling).

So, for example, a connector URL of `https://example.com/connector1` could use: 

`https://example.com/.well-known/dspace-trust/connector1`
