### ISSUE TITLE
Fix Schemas, Shapes, Examples, and Diagrams for Transfer Messages

### ISSUE THREAD

**Issue by sebbader-sap** [International-Data-Spaces-Association/ids-specification#168]
The files in the [transfer](https://github.com/International-Data-Spaces-Association/ids-specification/tree/main/transfer) section need to be reworked and fixed.

**Comment by ssteinbuss** [comment]
fixed by #173

**Comment by sebbader-sap** [comment]
Actually, not solved #173 (was heavily outdated) but #184
