### ISSUE TITLE
Enhance the "Model" Section

### ISSUE THREAD

**Issue by sebbader-sap** [International-Data-Spaces-Association/ids-specification#169]
The declaration of classes in [model](https://github.com/International-Data-Spaces-Association/ids-specification/tree/main/model) is incomplete. We need to provide a comprehensive list before releasing the protocol.

**Comment by ssteinbuss** [comment]
@sebbader-sap please add more details

**Comment by matgnt** [comment]
e.g. Dataspace Registry is not explained in text

**Comment by ssteinbuss** [comment]
I will check the the terminology for data space authority and its registry and add a note that this is not covered in this spec

**Comment by ssteinbuss** [comment]
registry is in the first figure

**Comment by ssteinbuss** [comment]
Split section 2.1 in non normative first part and normative part starting with the second figure

**Comment by ssteinbuss** [comment]
AssetEntry needs to be removed from figure 2
