### ISSUE TITLE
Synchronize Schemas and Shapes with the Context File

### ISSUE THREAD

**Issue by sebbader-sap** [International-Data-Spaces-Association/ids-specification#170]

**Comment by ssteinbuss** [comment]
blocked by #173

**Comment by sebbader-sap** [comment]
Needs to be done after the model is finished completely.

**Comment by sebbader-sap** [comment]
Update: Solution included in #184

**Comment by sebbader-sap** [comment]
@mkollenstart please have a look at the context file again. To the best of my knowledge, and given the state as of today, we have it in a good state.
