### ISSUE TITLE
`signature` field not described in the ContractAgreementMessage

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#176]
The `signature` field is not described in the ContractAgreementMessage
https://github.com/International-Data-Spaces-Association/ids-specification/blob/0ad6f3c3d3210a66e99529acab4686292b265fd8/negotiation/contract.negotiation.protocol.md?plain=1#L126

(please add V1 label)

--
Matthias Binzer

**Comment by matgnt** [comment]
Also the way signatures are created is quite limited and not detailed enough for the impact it has.

https://github.com/International-Data-Spaces-Association/ids-specification/blob/0ad6f3c3d3210a66e99529acab4686292b265fd8/negotiation/contract.negotiation.protocol.md?plain=1#L258

How can we add information and open this up a bit to the actual instance of a dataspace to define?

I think the topic is very relevant for a V1 and needs more details.

**Comment by ssteinbuss** [comment]
Will be addressed during upcoming review of the document
