### ISSUE TITLE
`idsc` namespace is used in some examples, but not part of contex.json

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#191]
Example:
(and a few more in the same directory...)

https://github.com/International-Data-Spaces-Association/ids-specification/blob/eadbaa04bbed499eb76207e92e140535a5c367bc/catalog/message/example/dcat.distribution.example.json#L29

This namespace seems not to be defined

**Comment by juliapampus** [comment]
we should remove this as an example to avoid confusion by referring to the IDS Infomodel

**Comment by sebbader-sap** [comment]
closing it as `idsc` is not mentioned anymore in any of the files. In case I missed it somewhere, please open the issue again.
