### ISSUE TITLE
The Offer must NOT include an explicit target attribute

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#192]
```
The Offer must NOT include an explicit target attribute
```
https://github.com/International-Data-Spaces-Association/ids-specification/blob/eadbaa04bbed499eb76207e92e140535a5c367bc/model/model.md?plain=1#L70

but examples do contain the `target`, e.g. here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/ca29dbf6e720bf2a1304d6d4fd3dc963a49fcb10/negotiation/message/contract-request-message.json#L7

and also diagrams do contain the `target` as for example here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.protocol.md#1-contractrequestmessage

--
Matthias Binzer

**Comment by matgnt** [comment]
can someone tag this with v1 pre release, please?

**Comment by juliapampus** [comment]
Maybe we should distinguish the offers in the catalog from the offers within negotiation messages. The latter do have a `target` attribute.

**Comment by matgnt** [comment]
Yes, I agree. That was exactly also my conclusion :-)

**Comment by jimmarino** [comment]
See #193

**Comment by matgnt** [comment]
I think we should not add this redundancy. There is also examples in Dcat explaining the situation as we have it right now, meaning the target is given by the enclosing context:
https://www.w3.org/TR/vocab-dcat-3/#ex-odrl-policy

```
The above example does not explicitly define the ODRL Asset, so assumes the enclosing identified entity is the subject of the policy
```

**Comment by matgnt** [comment]
Update from the meeting today:

Catalog -> Dataset -> hasPolicy (Offer) MUST NOT or SHOULD NOT (still discussing...) contain the `target` but rather use the enclosing datasetId.

The contractRequestMessage -> dspace:Offer (Offer) MUST contain the `target` (as there is no enclosing context).
The `datasetId` from the contractRquestMessage will be removed.

@sebbader @jimmarino

**Comment by matgnt** [comment]
Update from the meeting today:
> 
> Catalog -> Dataset -> hasPolicy (Offer) MUST NOT or SHOULD NOT (still discussing...) contain the `target` but rather use the enclosing datasetId.

We agreed for "MUST NOT"
