### ISSUE TITLE
Change `dspace:providerId` to use `assigner` instead - and `dspace:consumerId` to `assignee`

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#195]
As described in ODRL
https://www.w3.org/TR/odrl-model/#policy-offer
an `Offer` MUST have one `assigner`. Which is basically what has been intended with `dspace:providerId`.

An `Agreement` MUST have both, `assigner` AND `asignee`

As described for compact policies:
https://www.w3.org/TR/odrl-model/#composition-compact
these properties can be set on the Policy level and being applied to all its rules.

**In the catalog** we will use the same mechanism as we do with the `target` (#192 ). The `assigner` needs to be coming from the enclosing context. Here, not the `dataset` but the `Catalog`.
This requires #196  to introduce a `participantId` on `Catalog` level!

In `ContractRequestMessage->dspace:offer` the `assigner` needs to be set (on the Offer/Policy level!) (The value is a `participantId`)
(We agreed to alwys use 'compact Policy' form and we need to 'profile' this. TODO)

Similar for `assignee`. This is a MUST in an `Agreement` and will replace `dspace:consumerId`.

Beware, that `assigner` and `asignee` are of type `Party` and require to be an IRI. Pure literals are not allowed.

Any further comments @jimmarino @sebbader-sap ?

CC: @juliapampus @ssteinbuss 

--
Matthias Binzer

**Comment by wolf4ood** [comment]
Hi @matgnt 

that means that in this example payload:

https://github.com/International-Data-Spaces-Association/ids-specification/blob/ca29dbf6e720bf2a1304d6d4fd3dc963a49fcb10/negotiation/message/example/contract.agreement.message.http.transfer.json#L1-L20


`dspace:providerId` and `dspace:consumerId` at root level will be replaced by  `assigner` and `assignee`  in the odrl Agreement?

Thanks

**Comment by matgnt** [comment]
> `dspace:providerId` and `dspace:consumerId` at root level will be replaced by `assigner` and `assignee` in the odrl Agreement?
> 
> Thanks

correct

**Comment by sebbader-sap** [comment]
@SimantVerma-Bcone can you have a look at that and check:

- [ ] Check the Markdown file for the negotiation section
- [ ] adjust the schemas for the messages, and
- [ ] adjust the shapes, and 
- [ ] check the examples again

Thanks!
