### ISSUE TITLE
Introduce `participantId` on `Catalog` level

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#196]
For #195 we need a `participantId` on the `Catalog` level. This gives context to dataset->has_policy and will be used e.g. in `ContractRequestMessage->dspace:offer->assigner`

--
Matthias Binzer

**Comment by matgnt** [comment]
TODO: check if and what is the difference compared to `dct:publisher`: 
https://github.com/International-Data-Spaces-Association/ids-specification/blob/e87eb2a352ec89e6b8c1e26809d8b60c33d002c6/catalog/message/example/catalog.json#L12

**Comment by sebbader-sap** [comment]
to be started after https://github.com/International-Data-Spaces-Association/ids-specification/pull/184

**Comment by ssteinbuss** [comment]
* We should explain the relationship to the ODRL attributes 'assigner' and 'assignee' 
* This might not be just a string, but an IRI
* Check also the relationship to 'dct:publisher' (see above)
