### ISSUE TITLE
Inconsistency in ContractRequestMessage

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#198]
In the [procotol](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.protocol.md#1-contractrequestmessage), we define that a `ContractRequestMessage` contains either a `dspace:offer` or `dspace:offerId`. This is not reflected in the [schema](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/message/schema/contract-request-message-schema.json).

**Comment by matgnt** [comment]
@juliapampus where exactly? I can't find the text that allows dspace:offerId

**Comment by juliapampus** [comment]
@matgnt Oh sry, wrong link.. here is the section: https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.binding.https.md#261-post

**Comment by juliapampus** [comment]
could be a leftover?

**Comment by IgorBalog-Eng** [comment]
While we review this file, there are broken json examples, that are missing comma at the end

{
  "@context": "https://w3id.org/dspace/v0.8/context.json",
  "@type": "dspace:ContractRequest"    <----- here missing comma
  "dspace:consumerPid": "urn:uuid:32541fe6-c580-409e-85a8-8a9a32fbe833",
  
  and also in next json example and
  3.2.1 POST
  "@context": "https://w3id.org/dspace/v0.8/context.json",
  "@type": "dspace:ContractOfferMessage"    <--- here
  "dspace:providerPid": "urn:uuid:dcbf434c-eacf-4582-9a02-f8dd50120fd3",
  
and its response example

**Comment by ssteinbuss** [comment]
should be fixed with #184

**Comment by juliapampus** [comment]
will check again before closing the issue

**Comment by juliapampus** [comment]
I can't find any more inconsistencies.
