### ISSUE TITLE
Missing `dataset` property in Dataset Request Message

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#199]
The schemes and shapes for the `DatasetRequestMessage` and the `CatalogRequestMessage` look alike although the [spec](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.protocol.md) states:
> The `DatasetRequestMessage` must have a [Dataset](../model/terminology.md#dataset) property which contains the id of the [Dataset](../model/terminology.md#dataset).

**Comment by ssteinbuss** [comment]
need to be addressed in the editorial rework branch, see #184 
https://github.com/International-Data-Spaces-Association/ids-specification/blob/editorial-rework/catalog/message/diagram/dataset-request-message.png

**Comment by sebbader-sap** [comment]
I can confirm, fixed with https://github.com/International-Data-Spaces-Association/ids-specification/commit/815aedcafab4eca17751eade9dec754b4de15bac
