### ISSUE TITLE
What is the `wellknown` sub separation?

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#202]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/164206dbe2a5933c5344940216de62832811e381/catalog/catalog.binding.https.md?plain=1#L141

What is the `connector1` here? The `participantId`? We should explicitly say this.

**Comment by matgnt** [comment]
Same here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/e87eb2a352ec89e6b8c1e26809d8b60c33d002c6/common/common.binding.https.md?plain=1#L13

**Comment by matgnt** [comment]
Should we maybe move this thing outside of the `catalog.bining.https.md` into the `common.*` part? At least the part with multiple connectors...

**Comment by ssteinbuss** [comment]
@matgnt provides more context and validates against the RFC
