### ISSUE TITLE
Move out `Authorization` sections into 1 single place in `Common`?

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#203]
I would suggest to move out the different `Authorization` sections from within (https binding) `Catalog`, `Negotiation` and `Transfer` into a singel place in `Common`.

Any thoughts?

**Comment by sebbader-sap** [comment]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.binding.https.md#31-authorization
