### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by arnoweiss** [International-Data-Spaces-Association/ids-specification#208]
This link is broken and appears to have been a placeholder all along.

https://github.com/International-Data-Spaces-Association/ids-specification/blob/e464d64f421a4e95abaeb45ab88991c8a80a3546/catalog/catalog.binding.https.md?plain=1#L7

**Comment by sebbader-sap** [comment]
#184 rewrites this line.

**Comment by sebbader-sap** [comment]
I'll keep this issue open until the PR is merged.
