### ISSUE TITLE
Upgrade @context Link to the Pre-Release Version

### ISSUE THREAD

**Issue by sebbader-sap** [International-Data-Spaces-Association/ids-specification#224]
Currently, we use "@context": "https://w3id.org/dspace/v0.8/context.json". However, as the "v0.8" is not the version that we will publish, we need to find a proper version tag and then use it to replace it everywhere.

**Comment by sebbader-sap** [comment]
Related to #15 regarding the version tag of our to-be-published version.

**Comment by sebbader-sap** [comment]
Proposals:
1. https://w3id.org/dspace/v0.9/context.json
1. https://w3id.org/dspace/0/9/context.json
1. https://w3id.org/dspace/2024/context.json
1. https://w3id.org/dspace/pre-release/context.json

**Comment by sebbader-sap** [comment]
I think Option 3 is a good compromise to prevent conflicts with later versions but also prevent a "pre-release" path segment.

**Comment by ssteinbuss** [comment]
https://w3id.org/dspace/2024/1/context.json it is as decided in the meeting today

@sebbader-sap will make a PR towards the w3id fork

**Comment by sebbader-sap** [comment]
Required steps:
- [ ] changes of #237 
- [ ] changes of #233 
- [ ] move content from root to a releases/2024-1 folder
- [ ] prepare PR for w3id with the new locations
