### ISSUE TITLE
`context.json` file malformed.

### ISSUE THREAD

**Issue by ndr-brt** [International-Data-Spaces-Association/ids-specification#263]
the released context file is malformed, a comma is missing at line 58:

https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/releases/2024-1/common/schema/context.json#L58

(same for the `main` unreleased version)

**Comment by matgnt** [comment]
Ref: https://github.com/International-Data-Spaces-Association/ids-specification/issues/232#issuecomment-2024585943

**Comment by sebbader-sap** [comment]
Solved with https://github.com/International-Data-Spaces-Association/ids-specification/pull/264
