### ISSUE TITLE
Focus on "data access" or "data usage" contracts?

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#32]
From the introduction:
> How contract agreements that govern data access are syntactically expressed and electronically negotiated.

could this be changed into maybe
> How contract agreements that govern data access AND/OR data usage are syntactically expressed and electronically negotiated.

The question behind might be a bit larger:
During discussions I learned that negotiated agreement should eventually replace existing legal ("paper") contracts. If we follow this picture, we need to ask what is the granularity of those "paper" contracts today.
Example:
A supplier produces LED lights of a certain type, let's say 'FancyLedLight'. the supplier produces 1 Billion of those things and each get a serial number 00000...1 00000...2 and so on.

Do we create and negotiate an agreement for each and every serial number? If not, and we say we create 1 an asset for the type (FancyLedLight) because the policies is the same for all of those produced 'instances' of the part, we might get additional access decisions in the data source / backend system (e.g. based on the requester's identity). In such a use case, the clear benefit is the negotiated usage policy, BUT access needs to be handled separately / additionally, e.g. attribute based (ABAC) with additional information from e.g. a sales database.

I hope the slightly longer example helps to explain my question :-)

**Comment by arnoweiss** [comment]
This appears to remain relevant as neither "access control" nor "discoverability" have been added to the terms [1].

[1] https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/overview/terminology

**Comment by PeterKoen-MSFT** [comment]
access control and discoverability are generic and common terms in IT and for developers. I don't think that we need to add those to the IDSA specific terminology.
