### ISSUE TITLE
Define ids:DataPlaneType

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#40]
`TransferRequestMessage` is referring to a data exchange format that we, as example, set to an IDS enum. We need to have further discussions to come to a decision about that. Should the IDSA predefine transfer protocols or should adopters/users of this protocol agree on existing standards/be free to define new ones?

**Comment by abhishekmaha-tno** [comment]
Is this currently under discussion? This would allow participants to define their own protocols and publish data-planes.

**Comment by juliapampus** [comment]
Resolved with #164
