### ISSUE TITLE
Fix dataset reference in the Catalog Protocol specification

### ISSUE THREAD

**Issue by jimmarino** [International-Data-Spaces-Association/ids-specification#48]
The dataset reference in catalog/catalog.protocol.md needs to be fixed:

**Response**: [Dataset](#22-catalog) containing the [DCAT Dataset](https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset).

per @sebbader:

>The data object in 2.2 is a dcat:Catalog, not a dcat:Dataset. Even though dcat:Catalog inherits from dcat:Dataset, I guess we need an own schema for it.

**Comment by sebbader-sap** [comment]
We have a schema for Dataset by now, so I think we can close this issue.
