### ISSUE TITLE
Differences between `TransferTerminationMessage` and `TransferError`

### ISSUE THREAD

**Issue by ndr-brt** [International-Data-Spaces-Association/ids-specification#57]
Reading through the [Transfer Process protocol](https://github.com/International-Data-Spaces-Association/ids-specification/blob/a98e3d4ee6f774e8a48b5ce9f4ff1b07db20b86d/transfer/transfer.process.protocol.md) file it's not really clear when a `TransferTerminationMessage` should be preferred to a `TransferError`.

Seems that the first causes a termination of the transfer, while the latter not, but maybe it would be better to detail in which cases `TransferError` could be used and how to interpret it.

**Comment by juliapampus** [comment]
As stated in the document, the `TransferError` is not a message that can be actively send by a provider or consumer like a `TransferTerminationMessage` or some other transfer messages:

> It does not cause a state transition.

In the HTTP binding document, the `TransferError` is defined as the response body (code 4xx) resulting from an unsuccessful transfer message. The document also states

> If an error body is returned [...]

The _if_ implies that the error can be sent but must not, so we don't predefine further processing.

I agree, we could specify this further, especially within the specifications for the bindings.

**Comment by ndr-brt** [comment]
Ok, got it, so it's the equivalent of a failed response in the REST binding, it would be effectively used only on an asynchronous channel (like a MQ or similar).

Maybe ACK and KO could be described both in a different section, explaining that in a REST binding they are represented by the successful response and the failed one respectively.
