### ISSUE TITLE
Explain "IRI"

### ISSUE THREAD

**Issue by ndr-brt** [International-Data-Spaces-Association/ids-specification#64]
In the contract negotiation specification it's stated that
https://github.com/International-Data-Spaces-Association/ids-specification/blob/3f9fc7c776bc9273f4df32b49c90c910df23b1fb/negotiation/contract.negotiation.protocol.md?plain=1#L17

But it's not explained what an `IRI` is, I looked in all the repository but cannot find anything related.
Maybe it's just a typo of `URI`

**Comment by juliapampus** [comment]
https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier

**Comment by juliapampus** [comment]
We could add a reference to the spec or introduce the abbreviation.
