### ISSUE TITLE
Wrong ID in contract-negotiation.json

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#73]
The `contract negotiation` has an `@id` and `dspace:processId`. The second one should be the `correlationId` (comparable to the transfer process).

**Comment by sebbader-sap** [comment]
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/message/contract-negotiation.json

**Comment by sebbader-sap** [comment]
I don't remember when we used processId and when correlationId. @juliapampus, the (negation) messages have the processId attribute. Which is correct, right?

**Comment by juliapampus** [comment]
See https://github.com/International-Data-Spaces-Association/ids-specification/issues/79#issuecomment-1515911386
