### ISSUE TITLE
https://w3id.org/dspace/v0.8/context.json is a 404

### ISSUE THREAD

**Issue by albertoabellagarcia** [International-Data-Spaces-Association/ids-specification#78]
@context link https://w3id.org/dspace/v0.8/context.json is a 404 error. is it right?

**Comment by juliapampus** [comment]
This is an example link, so a 404 is correct.

**Comment by sebbader-sap** [comment]
Merge into https://github.com/International-Data-Spaces-Association/w3id.org/tree/master/dspace

**Comment by ssteinbuss** [comment]
@mkollenstart will validate the redirects. Please comment here with your results.

**Comment by ssteinbuss** [comment]
fixed, following issue is #171
