### ISSUE TITLE
Unneeded `correlationId` attribute in the `TransferProcess` messages

### ISSUE THREAD

**Issue by ndr-brt** [International-Data-Spaces-Association/ids-specification#79]
The `TransferProcess` messages bring, in addition to `processId`, a `correlationId`, that, in fact, it is not needed:
as done in the `ContractNegotiation`, the `processId` will represent a correlation id that could be used by both parts to identity the same CN/TP. It will be enough for the scope.

**Comment by sebbader-sap** [comment]
Decision from the meeting on 20.04.2023: Group agrees that the `correlationId` does not contain relevant information, therefore we will remove it from all messages.
