### ISSUE TITLE
dspace:checksum seems to be not explained anywhere int the spec

### ISSUE THREAD

**Issue by matgnt** [International-Data-Spaces-Association/ids-specification#91]
`dspace:checksum` is used in the example here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/message/contract-negotiation.json
but not in the http binding here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.binding.https.md#241-get

and it seems it is not described anywhere in the document. At least I couldn't find it with git grep.

---
Matthias Binzer

**Comment by jimmarino** [comment]
This should be removed. We had the idea of sending checksums for ensuring synchronization between consumer and provider but it is not really needed.
