### ISSUE TITLE
Handling Participant Ids in the Contract Agreement

### ISSUE THREAD

**Issue by jimmarino** [International-Data-Spaces-Association/ids-specification#92]
Currently, the `ContractAgreementMessage` does not contain properties for the participant ids. Two properties should be defined of type xsd:string:

- `dspace:consumerId`
- `dspace:providerId`

The contents of these properties are a dataspace-specific unique identifier of the contract agreement parties. Note that these identifiers are not necessarily the same as the identifiers of the participant agents negotiating the contract (i.e. the "connectors").

**Comment by juliapampus** [comment]
Should be added to the `odrl:Agreement`, not `dspace:ContractAgreementMessage`.
